application: homework06
version: 1
runtime: php55
api_version: 1

handlers:

- url: /
  static_files: main.html
  upload: main.html

- url: /(.*\.(css$|js$))
  static_files: \1
  upload: (.*\.(css$|js$))

- url: /.*
  script: place.php #was main.php
